#!/usr/bin/env bash

##############################################################################
#                                                                            #
#   _             _                _                                         #
#  | |__    ___  | | __         __| |  __ _   ___  _ __ ___    ___   _ __    #
#  | '_ \  / _ \ | |/ / _____  / _` | / _` | / _ \| '_ ` _ \  / _ \ | '_ \   #
#  | | | || (_) ||   < |_____|| (_| || (_| ||  __/| | | | | || (_) || | | |  #
#  |_| |_| \___/ |_|\_\        \__,_| \__,_| \___||_| |_| |_| \___/ |_| |_|  #
#                                                                            #
# Copyright (C) 2024-2025 qwardo <odrawq.qwardo@gmail.com>                   #
#                                                                            #
# This file is part of hok-daemon.                                           #
#                                                                            #
# hok-daemon is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by       #
# the Free Software Foundation, either version 3 of the License, or          #
# (at your option) any later version.                                        #
#                                                                            #
# hok-daemon is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
# GNU General Public License for more details.                               #
#                                                                            #
# You should have received a copy of the GNU General Public License          #
# along with hok-daemon. If not, see <http://www.gnu.org/licenses/>.         #
#                                                                            #
##############################################################################

readonly ERRORSTAMP="\033[31;1mError:\e[0m"
readonly CONFIG_FILE="include/config.h"

if [[ -f $CONFIG_FILE ]]; then
    bot_token=$(sed -n -E 's/^\s*#define BOT_TOKEN\s+"(.*)"/\1/p' $CONFIG_FILE)
    root_chat_id=$(sed -n -E 's/^\s*#define ROOT_CHAT_ID\s+(.+)/\1/p' $CONFIG_FILE)
fi

read -p "Telegram bot token: " new_bot_token
bot_token=${new_bot_token:-$bot_token}

if [[ -z $bot_token ]]; then
    echo -e "$ERRORSTAMP telegram bot token is empty"
    exit 1
fi

read -p "Administrator user id: " new_root_chat_id
root_chat_id=${new_root_chat_id:-$root_chat_id}

if [[ -z $root_chat_id ]]; then
    echo -e "$ERRORSTAMP administrator user id is empty"
    exit 1
fi

echo "// This file is autogenerated by configure.sh.

#ifndef CONFIG_H
    #define CONFIG_H

    #define BOT_TOKEN    \"$bot_token\"
    #define ROOT_CHAT_ID $root_chat_id

#endif" > $CONFIG_FILE

echo -e "\e[0;32;1mConfiguration done\e[0m"
